version: '3'

# run tests:  cd ci/unit; docker-compose up --build --force-recreate
# manual:  cd ci/unit; docker-compose run logstash bash
services:

  logstash:
    build:
      context: ../../
      dockerfile: ci/unit/Dockerfile
      args:
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
        - DISTRIBUTION=${DISTRIBUTION:-default}
        #- INTEGRATION=false
    command: /usr/share/plugins/plugin/ci/unit/run.sh
    env_file: docker.env
    environment:
      - SPEC_OPTS
    tty: true
